import React, { createContext, useContext, useReducer } from 'react';

/*this is the data layer,  A data layer is a layer of your website which contains all of the data
that gets generated by visitors engaging with your website. Not all websites have a data layer, but having one enables
more reliable and flexible data collection.*/
export const StateContext = createContext();

/*apparently this is a higher order component, Concretely, a higher-order component is a function
that takes a component and returns a new component*/
export const StateProvider = ({ reducer, initialState, children }) => (
    <StateContext.Provider value={useReducer(reducer, initialState)}>
        {/*the children is the <App/> component in the index.js file, they are both the same thing*/}
        {children}
    </StateContext.Provider>
);

//this hook allows us to pull info from the data layer
export const useStateValue = () => useContext(StateContext);